insert into public.plans (
  id,
  code,
  name,
  audience,
  kind,
  billing_interval,
  currency,
  price_amount_minor,
  points_grant,
  is_active,
  display_order,
  description,
  metadata_payload
)
values
  (
    '2d6a6c9e-5e06-4da4-9d92-3e5d3c30a001',
    'recruiter_starter_monthly',
    'Recruiter Starter',
    'recruiter',
    'subscription',
    'monthly',
    'SAR',
    null,
    0,
    true,
    1,
    'Starter monthly subscription for recruiter accounts.',
    null
  ),
  (
    '2d6a6c9e-5e06-4da4-9d92-3e5d3c30a002',
    'recruiter_growth_monthly',
    'Recruiter Growth',
    'recruiter',
    'subscription',
    'monthly',
    'SAR',
    null,
    0,
    true,
    2,
    'Growth monthly subscription for recruiter accounts.',
    null
  ),
  (
    '2d6a6c9e-5e06-4da4-9d92-3e5d3c30a003',
    'recruiter_scale_monthly',
    'Recruiter Scale',
    'recruiter',
    'subscription',
    'monthly',
    'SAR',
    null,
    0,
    true,
    3,
    'Scale monthly subscription for recruiter accounts.',
    null
  ),
  (
    '2d6a6c9e-5e06-4da4-9d92-3e5d3c30a004',
    'jobseeker_monthly_29_sar',
    'Jobseeker Monthly',
    'jobseeker',
    'subscription',
    'monthly',
    'SAR',
    2900,
    0,
    true,
    4,
    '29 SAR monthly subscription for jobseeker accounts.',
    null
  )
on conflict (code) do update set
  name = excluded.name,
  audience = excluded.audience,
  kind = excluded.kind,
  billing_interval = excluded.billing_interval,
  currency = excluded.currency,
  price_amount_minor = excluded.price_amount_minor,
  points_grant = excluded.points_grant,
  is_active = excluded.is_active,
  display_order = excluded.display_order,
  description = excluded.description,
  metadata_payload = excluded.metadata_payload,
  updated_at = now();
