from sqlalchemy import Float, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin


class InterviewSession(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A single AI interview session — questions generated by GPT, answers evaluated per-turn."""

    __tablename__ = "interview_sessions"

    user_id: Mapped[str] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    job_title: Mapped[str] = mapped_column(String(255), nullable=False)
    experience_level: Mapped[str] = mapped_column(String(20), nullable=False)  # entry | mid | senior
    interview_type: Mapped[str] = mapped_column(String(20), nullable=False)   # hr | technical | mixed
    language: Mapped[str] = mapped_column(String(10), nullable=False, default="en", server_default="en")
    question_count: Mapped[int] = mapped_column(Integer, nullable=False, default=5, server_default="5")

    # [{index, question, type}]
    questions: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # [{index, question, answer, evaluation: {score, strengths, weaknesses, improved_answer}}]
    answers: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    overall_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # {summary, readiness, breakdown: {relevance, clarity, professionalism, confidence, role_fit}}
    final_report: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="active", server_default="active", index=True
    )  # active | completed

    user = relationship("User", back_populates="interview_sessions")
